export default {
  blocks: [
    'wrapper',
    'sect100',
    'sect50',
    'sect30',
    'sect37',
    'button',
    'divider',
    'text',
    'text-sect',
    'image',
    'quote',
    'link',
    'link-block',
    'grid-items',
    'list-items',
  ],
  block: () => ({}),
  juiceOpts: {},
  cmdOpenImport: 'gjs-open-import-template',
  cmdTglImages: 'gjs-toggle-images',
  cmdInlineHtml: 'gjs-get-inlined-html',
  modalTitleImport: 'Import template',
  modalTitleExport: 'Export template',
  modalLabelImport: '',
  modalLabelExport: '',
  modalBtnImport: 'Import',
  codeViewerTheme: 'hopscotch',
  importPlaceholder: '',
  inlineCss: true,
  cellStyle: {
    padding: '0',
    margin: '0',
    'vertical-align': 'top',
  },
  tableStyle: {
    height: '150px',
    margin: '0 auto 10px auto',
    padding: '5px 5px 5px 5px',
    width: '100%',
  },
  updateStyleManager: true,
  showStylesOnChange: true,
  showBlocksOnLoad: true,
  useCustomTheme: true,
  primaryColor: '#373d49',
  secondaryColor: '#dae5e6',
  tertiaryColor: '#4c9790',
  quaternaryColor: '#35d7bb',
  i18n: {},
};
