export default {
  blocks: [
    'mj-1-column',
    'mj-2-columns',
    'mj-3-columns',
    'mj-text',
    'mj-button',
    'mj-image',
    'mj-divider',
    'mj-social-group',
    'mj-social-element',
    'mj-spacer',
    'mj-navbar',
    'mj-navbar-link',
    // 'mj-hero',
    'mj-wrapper',
    // 'mj-raw',
  ],
  block: () => ({}),
  codeViewerTheme: 'hopscotch',
  importPlaceholder: '',
  imagePlaceholderSrc: '',
  overwriteExport: true,
  preMjml: '',
  postMjml: '',
  resetBlocks: true,
  resetStyleManager: true,
  resetDevices: true,
  hideSelector: true,
  useXmlParser: false,
  useCustomTheme: true,
  columnsPadding: '10px 0',
  i18n: {},
  fonts: {},
  // Export 'mjml', 'html' or both (leave empty) TODO
  // exportOnly: '',
  primaryColor: '#14cc97',
  secondaryColor: '#fff',
  tertiaryColor: '#fff',
  quaternaryColor: '#fff',
};
